shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
   # path('registration_order/', views.order_create, name='order'),
]

shop/order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('registration_order/', views.order_create, name='order'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('users.urls'))

]

shop/cart/models.py
from django.db import models
from users.models import CustomUser


class CartItem(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, to_field='id')
    products = models.TextField(default='Пусто')

shop/order/models.py
from django.db import models
from users.models import CustomUser
from catalog.models import Product


class Order(models.Model):
    id = models.BigAutoField(primary_key=True)
    id_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, to_field='id')
    phone = models.TextField(help_text='телефон заказчика', null=True)
    email = models.EmailField(help_text='Email', null=True)
    structure = models.TextField(default='Пусто', help_text='Состав заказа')
    cost = models.DecimalField(max_digits=15, decimal_places=2, default=0.00, help_text='Стоимость заказа')
    address = models.CharField(max_length=300, null=True, help_text='Адрес доставки')
    created_on = models.DateTimeField(auto_now_add=True, help_text='Время создания записи')

    class Meta:
        ordering = ('-created_on',)
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return 'Order {}'.format(self.id)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/order/forms.py
from django import forms


class AddOrder(forms.Form):
    phone = forms.CharField(min_length=1, max_length=15, label='Номер телефона')
    address = forms.CharField(min_length=1, max_length=250, label='Адрес доставки')
    email = forms.EmailField(min_length=1, max_length=100, label='Email')

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Product
from cart.models import CustomUser
from .cart import Cart
from .models import CartItem
from .forms import CartAddProductForm
import json


def cart_exist(request):
    cart_user = CartItem.objects.filter(id_user=request.user.id)
    if len(cart_user) != 1:
        cart = {}
        products = json.dumps(cart)
        cart_base = CartItem(id_user=CustomUser.objects.get(id=request.user.id), products=products)
        cart_base.save()
    return True


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    if request.user.is_authenticated:
        cart_exist(request)
        cart_base = CartItem.objects.get(id_user=request.user.id)
        cart.cart = json.loads(cart_base.products)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
        if request.user.is_authenticated:
            cart_exist(request)
            cart_base = CartItem.objects.get(id_user=request.user.id)
            cart_base.products = json.dumps(cart.cart)
            cart_base.save()
    return redirect('/cart/')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_base = CartItem.objects.get(id_user=request.user.id)
        cart.cart = json.loads(cart_base.products)
        cart.remove(product)
        cart_base.products = json.dumps(cart.cart)
        cart_base.save()
    else:
        cart.remove(product)
    return redirect('/cart/')


def cart_detail(request):
    if request.user.is_authenticated:
        cart_exist(request)
        cart_base = CartItem.objects.get(id_user=request.user.id)
        cart = Cart(request)
        cart.cart = json.loads(cart_base.products)
    else:
        cart = Cart(request)
    return render(request, 'detail.html', context={'cart': cart})

shop/order/views.py
from django.shortcuts import render
from cart.models import CustomUser
from cart.cart import Cart
from order.models import Order
from cart.models import CartItem
from .forms import AddOrder
import json


def order_create(request):
    if request.method == 'POST':
        cart = Cart(request)
        form = AddOrder(request.POST)
        if form.is_valid():
            order_data = form.cleaned_data
            phone = order_data['phone']
            address = order_data['address']
            email = order_data['email']
            if request.user.is_authenticated:
                cart_base = CartItem.objects.get(id_user=request.user.id)
                order = Order(id_user=CustomUser.objects.get(id=request.user.id),
                              phone=phone,
                              structure=json.dumps(cart.cart),
                              cost=cart.get_total_price(),
                              address=address,
                              email=email
                              )
                order.save()
                cart.cart = {}
                cart_base.products = json.dumps(cart.cart)
                cart_base.save()
        return render(request, 'order_complete.html', context={'order': order})
    form = AddOrder()
    cart = Cart(request)
    if request.user.is_authenticated:
        cart_base = CartItem.objects.get(id_user=request.user.id)
        cart.cart = json.loads(cart_base.products)
    return render(request, 'order.html', context={'form': form, 'cart': cart})

shop/cart/templates/detail.html
{% extends 'cart/detail.html' %}
{% block title %}
<title>
    Корзина
</title>
{% endblock %}

{% block content%}
<div class="block-names-product">
    <h1>Ваша корзина </h1>
</div>
<table align="center" class="cart" cols="6" width="80%" cellpadding="5">
    <thead>
    <tr bgcolor="#778899">
        <th></th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена</th>
        <th>Общая стоимость</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr bgcolor="#FFFAFA">
        <td>
            <img src="{{product.link}}"
                 style="width: 30%"

            >
        </td>
        <td>{{product.name}}</td>


        <td>


            {{item.quantity}}


        </td>


        <td><a href="{% url 'cart:cart_remove' product.id%}">
            <button type="button" class="btn-close" aria-label="Close"></button>
        </a></td>
        <td class="num">{{item.price}}</td>
        <td class="num">{{item.total_price}}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td bgcolor="#D3D3D3">Всего</td>
        <td bgcolor="#D3D3D3" colspan="4"></td>
        <td bgcolor="#D3D3D3" class="num">{{cart.get_total_price}}</td>
    </tr>
    </tbody>
</table>
{% if user.is_authenticated %}
<div style="height:100px">
    {% if cart.cart %}
    <a href="{% url 'order:order' %}">
        <br>
        <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-primary" type="button">Перейти к оформлению</button>
        </div>
    </a>
    <a href="/catalog/category">
        <br>
        <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-primary" type="button">Вернуться к каталогу</button>
        </div>
    </a>

    {% endif %}
</div>

{% else %}
<br>

<div style="height:100px">
    {% if cart.cart %}
    <a href="{% url 'users' %}">
        <br>
        <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-primary" type="button">Авторизация</button>
        </div>
    </a>
    <a href="/catalog/category">
        <br>
        <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-primary" type="button">Вернуться к каталогу</button>
        </div>
    </a>
<br>
    <div class="alert alert-primary d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
             class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img"
             aria-label="Warning:">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </svg>
        <div>
            Оформить заказ могут только авторизованные пользователи.
        </div>
    </div>

    {% endif %}
</div>

{% endif %}
{% endblock %}

shop/cart/templates/order.html
{% extends 'cart/detail.html' %}
{% load static %}
{% block title %}
<title>
    Оформление
</title>
{% endblock %}

{% block content%}
<div class="block-names-product">
    <h1>Оформление заказа </h1>
</div>


<table class="cart" width="100%" cols="6" cellpadding="5">
    <thead>
    <tr bgcolor="#778899">
        <th></th>
        <th>Товар</th>
        <th align="center">Количество</th>
        <th>Удалить</th>
        <th>Цена за ед.</th>
        <th>Общая стоимость</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr bgcolor="#FFFAFA">
        <td>
            <img src="{{product.link}}"
                 style="width: 20%">
        </td>
        <td align="left">{{product.name}}</td>
        <td align="center">{{item.quantity}}</td>
        <td align="left"><a href="{% url 'cart:cart_remove' product.id%}">
            <button type="button" class="btn-close" aria-label="Close"></button>
        </a></td>
        <td class="num" align="left">{{item.price}}</td>
        <td class="num" align="left">{{item.total_price}}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">

        <td bgcolor="#D3D3D3">Всего</td>
        <td bgcolor="#D3D3D3" colspan="4"></td>
        <td bgcolor="#D3D3D3" class="num">{{cart.get_total_price}}</td>
    </tr>
    </tbody>
</table>
<br>
<div class="str_order">
    <form name="order" method="post" action="{% url 'cart:order' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <div>

            <div class="d-grid gap-2 col-6 mx-auto">
                <button class="btn btn-primary" type="submit" value="order">Оформить заказ</button>
            </div>

        </div>
    </form>
</div>

{% endblock %}

shop/cart/templates/order_complete.html
{% extends 'cart/detail.html' %}
{% load static %}
{% block title %}
<title>
    Ваша корзина
</title>
{% endblock %}

{% block content %}
<div class = "block-names-product">
    <h3>Заказ №{{order.id}} на сумму {{order.cost}} рублей успешно оформлен! </h3>
</div>
<div style="height:100px">

</div>

{% endblock %}