shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
   # path('registration_order/', views.order_create, name='order'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('users.urls'))

]

shop/users/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.sign_in, name='users'),
    path('change_profile/', views.change_profile, name='change_profile'),
    path('change_data1/', views.change_data1, name='change_data1'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.sign_up, name='sign_up'),
    path('history/', views.history, name='history'),
    path('history/order_<int:order_id>', views.detail_order, name='detail_order'),
]

shop/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):

    name = models.CharField('Имя', max_length=255, default='')
    surname = models.CharField('Фамилия', max_length=255, default='')
    phone_number = models.CharField('Номер телефона', max_length=255, default='')
    email = models.EmailField('Электронная почта', max_length=255, default='')
    birth_date = models.DateField('Дата рождения', blank=True, default='2000-01-01', null=True)

shop/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class RegistrForm(forms.Form):
    username = forms.CharField(max_length=20, label='Логин')
    name = forms.CharField(max_length=20, label='Имя')
    surname = forms.CharField(max_length=20, label='Фамилия')
    phone_number = forms.CharField(max_length=20, label='Номер телефона')
    birth_date = forms.DateField(label="Дата рождения", help_text='YYYY-MM-DD')
    email = forms.EmailField(max_length=254, help_text='This field is required')
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)
    password_1 = forms.CharField(label="Повторите пароль", widget=forms.PasswordInput)


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'name', 'surname', 'email', 'phone_number', 'birth_date')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'name', 'surname', 'email', 'phone_number', 'username', 'birth_date')


class ChangeProfile(forms.Form):
    name = forms.CharField(label='Имя', required=False)
    surname = forms.CharField(label='Фамилия', required=False)
    phone_number = forms.DecimalField(label="Телефон", max_digits=11, decimal_places=0, required=False)
    email = forms.EmailField(label="Электронная почта", required=False)


class ChangeData1(forms.Form):
    username = forms.CharField(label='Логин', required=False)
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput, required=False)
    password_1 = forms.CharField(label="Повторите пароль", widget=forms.PasswordInput, required=False)

shop/users/views.py
from .models import CustomUser
from .forms import RegistrForm, ChangeProfile, ChangeData1
from catalog.models import Product
from order.models import Order
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
import json


def start(response):
    return render(response, "users/start.html")


def sign_up(request):
    if request.method == 'POST':
        form = RegistrForm(request.POST)
        if form.is_valid():
            data_user = form.cleaned_data
            data = {'form': form}
            if CustomUser.objects.filter(username=data_user['username']).exists():
                return render(request, 'users/form_registration_alert.html', data)
            if data_user['password_1'] == data_user['password']:
                del data_user['password_1']
                user = CustomUser.objects.create_user(**data_user)
                user.save()
                return render(request, 'users/form_complete.html')
            else:
                return render(request, 'users/form_registration_alert_password.html', data)
        else:
            data = {'form': form}
            return render(request, 'users/form_registration_alert.html', data)
    form = RegistrForm()
    data = {'form': form}
    return render(request, 'users/form_registration.html', data)


def login_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return render(request, 'users/login_success.html')
    else:
        return render(request, 'users/login.html')


def sign_in(request):
    return render(request, 'base2.html')


def logout_user(request):
    logout(request)
    return render(request, 'users/login.html')


def history(request):
    sell_base = Order.objects.filter(id_user=request.user.id)
    if sell_base:
        sell = Order.objects.filter(id_user=request.user.id)
    else:
        sell = None
    return render(request, 'users/history.html', context={'sell': sell})


def detail_order(request, order_id):
    order = Order.objects.get(id=order_id)
    cart = json.loads(order.structure)
    products = Product.objects.filter(id__in=cart.keys())
    for product in products:
        product.value = cart[str(product.id)]['quantity']
    cart['cost'] = order.cost
    return render(request, 'users/detail_order.html', context={'order': order, 'products': products, 'cart': cart})


def change_data1(request):
    user = CustomUser.objects.get(id=request.user.id)
    form = ChangeData1()
    if request.method == "POST":
        form = ChangeData1(request.POST)
        if form.is_valid():
            data_form = form.cleaned_data
            if data_form['username']:
                user.username = data_form['username']
            if data_form['password_1'] == data_form['password']:
                if data_form['password']:
                    user.set_password(data_form['password'])
            else:
                context = {'form': form}
                return render(request, 'users/change_data1_alert.html', context=context)
            user.save()
            return render(request, 'users/change_profile_complete.html')
    context = {'form': form}
    return render(request, 'users/change_data1.html', context=context)


def change_profile(request):
    user = CustomUser.objects.get(id=request.user.id)
    form = ChangeProfile()
    if request.method == "POST":
        form = ChangeProfile(request.POST)
        if form.is_valid():
            data_form = form.cleaned_data
            if data_form['name']:
                user.name = data_form['name']
            if data_form['surname']:
                user.surname = data_form['surname']
            if data_form['phone_number']:
                user.phone_number = data_form['phone_number']
            if data_form['email']:
                user.email = data_form['email']

            user.save()
            return render(request, 'users/change_profile_complete.html')
    context = {'form': form}
    return render(request, 'users/change_profile.html', context=context)

shop/users/templates/users/change_data1.html
{% extends 'base2.html' %}

{% block content %}
<form action="/change_data1/" name="change_data1" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Submit" style="float: left">
        <p>Завершить изменение</p>
    </button>
</form>
{% endblock %}

shop/users/templates/users/change_data1_alert.html
{% extends 'base2.html' %}

{% block content %}
<form action="/change_data1/" name="profile_update" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Пароли не совпадают
    </div>
    <div>
        <button type="submit" value="Submit" style="float: left">
            <p>Завершить изменение</p>
        </button>
    </div>
</form>
{% endblock %}

shop/users/templates/users/change_profile.html
{% extends 'base2.html' %}

{% block content %}
<form action="/change_profile/" name="profile_update" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Submit" style="float: left">
        <p>Завершить изменение</p>
    </button>
</form>
{% endblock %}

shop/users/templates/users/change_profile_alert.html
{% extends 'base2.html' %}

{% block content %}
<form action="/change_profile/" name="profile_update" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Пароли не совпадают
    </div>
    <div>
        <button type="submit" value="Submit" style="float: left">
            <p>Завершить изменение</p>
        </button>
    </div>
</form>
{% endblock %}

shop/users/templates/users/change_profile_complete.html
{% extends 'base2.html' %}
{% block content %}
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
<div class="alert alert-success d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <div>
    Данные успешно изменены
  </div>
</div>

{% endblock %}

shop/users/templates/users/detail_order.html
{% extends 'base2.html' %}

{% block content %}
<h2>
    Заказ № {{order.id}}
</h2>
<p>Время создания: {{order.created_on}}</p>
<p>Информация о покупателе: {{order.id_user}}, {{order.phone}}, {{order.email}}</p>
<table class="cart">
    <thead>
    <tr>
        <th></th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Цена</th>
    </tr>
    </thead>
    <tbody>
    {% for product in products %}
            <tr>
                <td>
                    <img src="{{product.link}}"
                         width="100"
                         height="100">
                </td>
                <td>{{product.name}}</td>
                <td align="center">{{product.value}}</td>
                <td class="num">{{product.price}}</td>
            </tr>
    {% endfor %}
    <tr class="total">
        <td>Всего</td>
        <td colspan="2"></td>
        <td class="num">{{cart.cost}}</td>
    </tr>
    </tbody>
</table>
{% endblock %}

shop/users/templates/users/form_complete.html
{% extends 'base2.html' %}

{% block content %}
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
<div class="alert alert-success d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <div>
    Регистрация прошла успешно
  </div>
</div>
<button type="submit" value="Log in" class="btn btn-light">
    <a href="{% url 'login' %}"> Войти </a>
</button>
{% endblock %}

shop/users/templates/users/form_registration.html
{% extends 'base2.html' %}

{% block content %}

<h2>
    Регистрация
</h2>
<form action="/signup/" name="register" method="post" autocomplete="off">

    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">
        Завершить регистрацию
    </button>

</form>
{% endblock %}

shop/users/templates/users/form_registration_alert.html
{% extends 'base2.html' %}

{% block content %}

<form action="/signup/" name="register" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Регистрация не удалась. Либо такой пользователь существует, либо данные введены неверно.
    </div>
    <div>
        <button type="submit" value="Submit" style="float: left">
            <p>Завершить регистрацию</p>
        </button>
    </div>
</form>
{% endblock %}

shop/users/templates/users/form_registration_alert_password.html
{% extends 'base2.html' %}

{% block content %}

<form action="/signup/" name="register" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Пароли не совпадают.
    </div>
    <div>
        <button type="submit" value="Submit" style="float: left">
            <p>Завершить регистрацию</p>
        </button>
    </div>
</form>
{% endblock %}

shop/users/templates/users/history.html
{% extends 'base2.html' %}

{% block content %}
<h2>
    История ваших заказов
</h2>
{% if sell %}
    {% for order in sell %}
    <a href="{% url 'detail_order' order.id%}"><p>Заказ №{{order.id}} на сумму {{order.cost}} рублей. Дата создания: {{order.created_on}}</p></a>
    {% endfor %}
{% else %}
    <p>Пусто</p>

{% endif %}
{% endblock %}

shop/users/templates/users/redir.html
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <meta charset="utf-8">
    {% block title %}

    {% endblock %}
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'users' %}">Личный кабинет</a>
                <a class="nav-link" href="{% url 'product' %}">Каталог</a>
                <a class="nav-link" href="{% url 'cart:cart' %}">Корзина</a>
            </div>
        </div>
    </div>
</nav>


{% block content %}
<div>
    {% if user.is_authenticated %}
    <h2>
        Приветствуем вас, {{user.username }} !
    </h2>
    <p>Имя: {{user.name}}</p>
    <br>
    <p>телефон: {{user.phone_number}}</p>
    <br>
    <p>Дата рождения: {{user.birth_date}}</p>
    <a href="{% url 'history'%}"><p>
        История заказов
    </p></a>
    <a href="{% url 'change_data1' %}"><p>Изменить логин/пароль</p></a>
    <a href="{% url 'change_profile' %}"><p>Изменить данные профиля</p></a>
    <a href="{% url 'logout' %}"><p>
        Выйти из аккаунта
    </p></a>
    {% else %}

    <p> Вы не авторизованы.</p>
    <button type="submit" value="Log in" class="btn btn-light">
        <a href="{% url 'login' %}"> Вход </a>
    </button>
    <button type="submit" value="Log in" class="btn btn-light">
        <a href="{% url 'sign_up' %}"> Регистрация </a>
    </button>
    {% endif %}
</div>
{% endblock %}
</body>
</html>